plantingcalendar/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("plantingcalendarapp/", include("plantingcalendarapp.urls")),
    path('admin/', admin.site.urls),
]

plantingcalendarapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<zip_code>/calendar", views.calendar, name="calendar"),
]

plantingcalendarapp/models.py
from IPython.core.completerlib import module_completer
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.

# Universal models
class USDAHardinessZone(models.Model):
    zone = models.CharField(max_length=10)
    description = models.CharField(max_length=1000)

    objects = models.Manager()

    def __str__(self):
        return f"{self.zone}: {self.description}"

class PlantSpecies(models.Model):
    name = models.CharField(max_length=200, default="")
    binomial = models.CharField(max_length=1000, default="")
    website =  models.CharField(max_length=1000, default="", null=True)
    needs_cold_stratify = models.BooleanField(default=False)
    needs_indoor_sow = models.BooleanField(default=False)
    can_direct_sow = models.BooleanField(default=False)
    objects = models.Manager()

    def __str__(self):
        return f"{self.name} ({self.binomial})"

# Plant Species subtype: Requires cold stratification
class PlantSpeciesColdStratify(PlantSpecies):
    cold_stratify_days_before_transplant = models.IntegerField()
    transplant_days_before_last_frost = models.IntegerField(default=0)

    objects = models.Manager()

# Plant Species subtype
class PlantSpeciesIndoorSow(PlantSpecies):
    indoor_sow_weeks_before_last_frost_min = models.IntegerField()
    indoor_sow_weeks_before_last_frost_max = models.IntegerField()
    objects = models.Manager()



# Plant Species subtype: Direct sow
class PlantSpeciesDirectSow(PlantSpecies):
    sow_weeks_before_last_frost = models.IntegerField()
    objects = models.Manager()




# Models for specific grower calendar

class Grower(models.Model):
    username = models.CharField(max_length=100, unique=True)
    objects = models.Manager()

    def __str__(self):
        return self.username

class GrowerCalendar(models.Model):
    grower = models.ForeignKey(
        Grower,
        models.PROTECT,
        blank=True,
        null=True
    ) #unique together
    station_id = models.IntegerField() # unique together
    name = models.CharField(max_length=1000)
    last_frost_date = models.DateTimeField()
    first_frost_date = models.DateTimeField()
    usda_hardiness_zone = models.ForeignKey(
        USDAHardinessZone,
        models.PROTECT,
        blank=True,
        null=True
    )
    objects = models.Manager()

    def __str__(self):
        return f"{self.grower} {self.station_id}"

    class Meta:
        unique_together = ('grower', 'station_id')

class GrowerPlant(models.Model):
    grower_calendar = models.ForeignKey(
        GrowerCalendar,
        models.PROTECT,
        blank=True,
        null=True
    )

    plant_species = models.ForeignKey(
        PlantSpecies,
        models.PROTECT,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.plant_species.name

    class Meta:
        unique_together = ('grower_calendar', 'plant_species')

    objects = models.Manager()


class GrowerPlantingEvent(models.Model):
    class PlantingEventType(models.TextChoices):
        INDOOR_SOW = 'INDOOR_SOW', _('🏡 Indoor sow')
        DIRECT_SOW = 'DIRECT_SOW', _('️️☀️Direct sow outdoors')
        TRANSPLANT = 'TRANSPLANT', _('🪴Transplant outdoors')
        COLD_STRATIFY = 'COLD_STRATIFY', _('❄️ Cold stratify')

    calendar = models.ForeignKey(
        GrowerCalendar,
        models.PROTECT,
        blank=True,
        null=True
    )
    event_type = models.CharField(max_length=100, choices=PlantingEventType, default=PlantingEventType.DIRECT_SOW)
    plant = models.ForeignKey(
        GrowerPlant,
        models.PROTECT,
        blank = True,
        null = True
    )
    event_code = models.CharField(max_length=200, default="")
    title = models.CharField(max_length=200, default="")
    description = models.CharField(max_length=1000, default="")
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    objects = models.Manager()

    def __str__(self):
        return f"{self.calendar} {self.event_type} {self.plant}"

    class Meta:
        unique_together = ('plant', 'event_type')

plantingcalendarapp/views.py
from django.http import HttpResponse

from plantingcalendarapp.helpers.data_fetcher import PHZmapi, FarmSenseStation
from plantingcalendarapp.models import *
from plantingcalendarapp.helpers.calendar_utils import get_dates_from_last_frost, create_planting_events_for_grower_calendar

def index(request):
    return HttpResponse("Hello, world. You're at Planting Calendar app.")


from django.shortcuts import render
from django.template import loader

# Create your views here.

def calendar(request, zip_code):
    phzmapi = PHZmapi()
    phzmapi.load_phzmapi_data(zip_code)
    calendar_dates = None

    fs = FarmSenseStation()
    fs.load_stations_from_coordinates(phzmapi.coordinate_lat, phzmapi.coordinate_long)
    if fs.farmsense_id:
        fs.load_frost_data_for_station(fs.farmsense_id)


    if fs.last_frost_date:
        zone = USDAHardinessZone.objects.get(zone=phzmapi.zone)
        # import ipdb; ipdb.set_trace()
        grower = Grower.objects.get(username='kayla')
        station_id = int(fs.farmsense_id)
        gc, created = GrowerCalendar.objects.get_or_create(
                grower=grower,
                station_id=station_id,
                name=f"Zone: {phzmapi.zone}; Station: {fs.farmsense_id} [{fs.name}]",
                last_frost_date=fs.last_frost_date,
                first_frost_date=fs.first_frost_date,
                usda_hardiness_zone=zone,
            )
        calendar_dates = get_dates_from_last_frost(gc)
        grower_planting_events = create_planting_events_for_grower_calendar(gc)
        grower_plants = GrowerPlant.objects.filter(grower_calendar=gc)

    zone_frost = {
        "zip_code": zip_code,
        "zone": phzmapi.zone,
        "station_name" : fs.name,
        "first_frost_date": fs.first_frost_date,
        "last_frost_date": fs.last_frost_date,
        "frost_calendar_dict": calendar_dates,
        "grower_planting_events": grower_planting_events,
        "grower_plants": grower_plants,
    }

    template = loader.get_template("plantingcalendarapp/index.html")
    context = {"zone_frost": zone_frost}
    return HttpResponse(template.render(context, request))

plantingcalendarapp/templates/plantingcalendarapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>farmstrong@home</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<div>

    <!-- Header -->
<header class="w3-container w3-green w3-center" style="padding:12px 16px">
            <h1 class="w3-margin w3-jumbo">farmstrong@home </h1>
            <p class="w3-xlarge"> Love home. Love community. Grow stuff.</p>
</header>
            <div class="w3-row-padding w3-padding-64 w3-container">
                Your zip code <b>{{zone_frost.zip_code}}</b> is in USDA Hardiness <b>Zone {{zone_frost.zone}}</b>

                <br/>
                Your estimated last frost in Spring is {{zone_frost.last_frost_date|date:"M d, Y"}}

                <br/>
                Your estimated first frost in Autumn is {{zone_frost.first_frost_date|date:"M d, Y"}}
                <br/>

                <h3>Your planting list</h3>
                <ul>
                    {% for gp in zone_frost.grower_plants %}
                    <li>
                    <a href="{{gp.plant_species.website}}" target="_blank">
                    <b>{{gp.plant_species.name}}</b>
                        (<i>{{gp.plant_species.binomial}}</i>)</a></li>
                    {% endfor %}
                </ul>

                <h3>Your personalized planting calendar</h3>
                {% for gpe in zone_frost.grower_planting_events %}
                <p>
                    {{gpe.get_event_type_display}}
                    <a href="{{gpe.plant.plant_species.website}}" target="_blank">
                    <b>{{gpe.plant.plant_species.name}}</b>
                    (<i>{{gpe.plant.plant_species.binomial}}</i>)</a>
                {{gpe.start_datetime|date:"M d"}} to {{gpe.end_datetime|date:"M d"}}.
                <br/><i>{{gpe.description}}</i></p>
                {% endfor %}


                <br/>


                <h3>Date references</h3>
                <p class="w3-text-grey">
                {% for key, value in zone_frost.frost_calendar_dict.items %}
                {{key}} weeks from last frost date is {{value|date:"M d"}} <br/>
                {% endfor %}

                <br/>
                <br/>
                </p>
            </div>
        </div>
    </section>
</div>
</body>
<footer  class="w3-container w3-padding-64 w3-center w3-opacity">
    <p>Your recommendations are based on your nearest USDA station at {{zone_frost.station_name}}</p>
    <p>&copy; 2025 farmstrong@home</p>
</footer>
<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>
</html>